name: Tavern

options:
  bundleIdPrefix: com.tavern
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "26.2"
  createIntermediateGroups: true
  defaultConfig: Debug
  fileTypes:
    icon:
      file: true  # Treat .icon bundles as single files (Icon Composer format)

settings:
  base:
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ENABLE_MODULE_VERIFIER: YES
    MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu11 gnu++14"
    STRING_CATALOG_GENERATE_SYMBOLS: YES

packages:
  ClodKit:
    path: /Users/yankee/Documents/Projects/ClodKit

targets:
  TavernCore:
    type: framework
    platform: macOS
    sources:
      - path: Sources/TavernCore
    dependencies:
      - package: ClodKit
        product: ClodKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tavern.core
      SWIFT_VERSION: "6.0"
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_NSHumanReadableCopyright: ""

  Tavern:
    type: application
    platform: macOS
    sources:
      - path: Sources/Tavern
    dependencies:
      - target: TavernCore
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tavern.app
      SWIFT_VERSION: "6.0"
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_NSHumanReadableCopyright: ""
      INFOPLIST_KEY_NSMainStoryboardFile: ""
      INFOPLIST_KEY_NSPrincipalClass: NSApplication
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_KEY_CFBundleIconName: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
    entitlements:
      path: Tavern.entitlements
      properties:
        com.apple.security.app-sandbox: false

  TavernUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: Tests/TavernUITests
    dependencies:
      - target: Tavern
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tavern.uitests
      SWIFT_VERSION: "6.0"
      GENERATE_INFOPLIST_FILE: YES
      TEST_TARGET_NAME: Tavern

schemes:
  Tavern:
    build:
      targets:
        Tavern: all
        TavernCore: all
        TavernUITests: [test]
    run:
      executable: Tavern
      config: Debug
    test:
      config: Debug
      targets:
        - TavernUITests
